[theme]

# Couleur principale (ton violet)
primaryColor = "#7b68ee"

# Fond principal (ton void)
backgroundColor = "#0f0e1a"

# Fond des containers / sidebar / widgets
secondaryBackgroundColor = "#1a1933"

# Couleur du texte principal
textColor = "#e8f5e9"

# Font globale (Ã©quivalent DM Sans)
font = "sans serif"

[server]
runOnSave = true